### Homepage
GET http://localhost:8080/home

### API: retrieve all actors
GET http://localhost:8080/api/actors

### API: retrieve all films
GET http://localhost:8080/api/films

### API: retrieve one actor (path variable)
GET http://localhost:8080/api/extraActorInfo/1

### API: retrieve one film (path variable)
GET http://localhost:8080/api/extraFilmInfo/2

### API: retrieve all films of one specific actor
GET http://localhost:8080/api/extraActorInfo/1/films

### API: retrieve all actors of one specific film
GET http://localhost:8080/api/extraFilmInfo/1/actors

### API: search actor
GET http://localhost:8080/actors/search?nationality=American&gender=M

### API: search film
GET http://localhost:8080/actors/search?actorName=Rami+Malek

### API: delete an actor
DELETE http://localhost:8080/api/extraActorInfo/2
Cookie: JSESSIONID=0896C8C2F7FAA5CC7B2AA7FD7E15491D
X-CSRF-TOKEN: l4agQY-ROCmc_MGnSNu_FRg_6fzXJYyFVd8RVYNGLhLjo31T8-LDeL6gDE-xxfiTLfaLInsPxMTnFOqoZr4hYLt0S3SGlkhh

### API: delete an film
DELETE http://localhost:8080/api/extraFilmInfo/1
Cookie: JSESSIONID=0896C8C2F7FAA5CC7B2AA7FD7E15491D
X-CSRF-TOKEN: l4agQY-ROCmc_MGnSNu_FRg_6fzXJYyFVd8RVYNGLhLjo31T8-LDeL6gDE-xxfiTLfaLInsPxMTnFOqoZr4hYLt0S3SGlkhh

### API: create an film (bad request)
POST http://localhost:8080/api/addFilm
Accept: application/json
Content-Type: application/json

{
  "filmName": "",
  "year": "2024-04-04",
  "boxOffice": 0.0,
  "genre": "SPY"
}

### API: create an actor (bad request)
POST http://localhost:8080/api/addActor
Accept: application/xml
Content-Type: application/xml


<actor>
    <actorName></actorName>
    <nationality>Spanish</nationality>
    <gender>Male</gender>
</actor>

### API: create an film (created)
POST http://localhost:8080/api/addFilm
Accept: application/json
Content-Type: application/json

{
  "filmName": "Sjkd",
  "year": "2021-02-02",
  "boxOffice": 220.0,
  "genre": "SPY"
}

### API: create an actor (created)
POST http://localhost:8080/api/addActor
Accept: application/xml
Content-Type: application/xml


<actor>
    <actorName>Actor</actorName>
    <nationality>Spanish</nationality>
    <gender>M</gender>
</actor>


### API: change an film's info (no content)

PATCH http://localhost:8080/api/extraFilmInfo/1
Content-Type: application/json

{
  "year": "2023-02-12",
  "boxOffice": 673.0,
  "genre": "SPY"
}

### API: change an film's info (not found)

PATCH http://localhost:8080/api/extraFilmInfo/1000
Content-Type: application/json

{
  "year": "2023-02-12",
  "boxOffice": 673.0,
  "genre": "SPY"
}

### API: change an film's info (bad request)

PATCH http://localhost:8080/api/extraFilmInfo/1
Content-Type: application/json

{
  "year": "02-12",
  "boxOffice": 0.0,
  "genre": "qw"
}

### API: change an actor's info (no content)

PATCH http://localhost:8080/api/extraActorInfo/1
Content-Type: application/json

{
"gender": "F",
"nationality": "Ukrainian"
}

### API: change an actor's info (not found)

PATCH http://localhost:8080/api/extraActorInfo/999
Content-Type: application/json

{
  "gender": "F",
  "nationality": "Ukrainian"
}

### API: change an actor's info (bad request)

PATCH http://localhost:8080/api/extraFilmInfo/2
Content-Type: application/json

{
  "gender": "F",
  "nationality": ""
}

